{{- if .Values.azure }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: gitops-updater-secretproviderclass
  namespace: "{{ .Release.Namespace }}"
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    keyvaultName: {{ .Values.azure.keyvaultName }}
    clientID: {{ .Values.azure.clientId }}
    tenantID: {{ .Values.azure.tenantId }}
    objects: |
      array:
       {{- range .Values.azure.secrets }}
        - |
          objectName: {{ . }}
          objectType: secret
       {{- end }}
{{- end }}