{{- if .Values.azure }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: {{ .Values.azure.clientId }}
  name: gitops-updater-sa
  namespace: "{{ .Release.Namespace }}"
{{- end }}